### PR TITLE
Issue665 filter

### LINKED ISSUE #665: Use same term for filteredOpening and filteredSpeed
This ticket is to discuss using for example `filteredInput` (or `use_input_filter`) instead of `filteredSpeed` for the movers and `filteredOpening` for the valves.

### PR DESCRIPTION
**Pull request by mwetter**
This closes #665.
@mlauster Can you please review and merge. I merged and tested it already for the Buildings library.

The conversion script is
```
// Renaming of filteredSpeed and filteredOpening
convertElement("IBPSA.Fluid.Movers.BaseClasses.PartialFlowMachine",
               "filteredSpeed", "use_inputFilter")
convertElement("IBPSA.Fluid.Actuators.BaseClasses.ActuatorSignal",
               "filteredOpening", "use_inputFilter")
```

### CODE REVIEW

**Comment by mlauster** [comment]
This PR contains some conflicts, @mwetter, could you take care of them?

**Comment by mwetter** [comment]
@mlauster I corrected the conflict. This is ready to merge from my point of view.

**Comment by mlauster** [comment]
We haven't yet merged IBPSA Library into AixLib, so I can't test the conversion scripts. But if it works for Buildings, I assume it will be fine for AixLib too. Does somebody would like to test it on IDEAS or BuildingSystems? From IBPSA Library point of view, this is ready to merge. I will merge tomorrow if no objections come up.

**Comment by Mathadon** [comment]
I'm not too worried about IDEAS. We can update our models when we update to a next version. For now I intend to stick with Annex60 v1.0 for a while.

**Pull request merged**
